# Generated by Django 4.0.6 on 2022-08-03 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_userdetails_approved_userdetails_denied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='Approved',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='Denied',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='room_no',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('Denied', models.BooleanField(default=False)),
                ('Approved', models.BooleanField(default=False)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
