# Generated by Django 4.0.6 on 2022-08-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_userdetails_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='room_no',
        ),
    ]
