# Generated by Django 4.0.6 on 2022-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_application_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='Ajay', max_length=20),
        ),
    ]
