# Generated by Django 4.0.6 on 2022-08-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_application_phone_number_application_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='ajay@gmail.com', max_length=100),
        ),
    ]
