# Generated by Django 4.0.6 on 2022-08-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_application_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Phone_number',
            new_name='phone',
        ),
    ]
