# Generated by Django 4.0.6 on 2022-08-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_phone_number_application_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
