# Generated by Django 4.0.6 on 2022-08-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
    ]
