# Generated by Django 4.0.6 on 2022-08-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_application_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='alloted_slot',
            field=models.IntegerField(default=0),
        ),
    ]
